// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import {IZKVerifier} from "./interfaces/IZKVerifier.sol";

/**
 * @title ZKVerifier
 * @author BharatRWA Team
 * @notice Wrapper around the auto-generated UltraVerifier from Barretenberg.
 * @dev This contract provides a clean interface for verifying Noir ZK-KYC proofs.
 *
 *      In production, the HonkVerifier contract is generated by running:
 *        nargo compile
 *        bb write_vk -b ./target/zk_kyc.json -o ./target/vk/ --verifier_target evm
 *        bb write_solidity_verifier -k ./target/vk/vk -o ./src/UltraVerifier.sol --verifier_target evm
 *
 *      For testing, we use a mock verifier that always returns true.
 *
 *      The proof verification flow:
 *      1. Investor generates ZK proof off-chain via Noir/Barretenberg
 *      2. Proof + public inputs are submitted to ComplianceManager
 *      3. ComplianceManager calls ZKVerifier.verify()
 *      4. ZKVerifier delegates to the auto-generated UltraVerifier
 */
contract ZKVerifier is IZKVerifier {
    // ============================================================
    //                          STATE
    // ============================================================

    /// @notice The auto-generated verifier contract from Barretenberg
    /// @dev This is set in the constructor and cannot be changed.
    ///      To upgrade the verifier, deploy a new ZKVerifier with the new UltraVerifier.
    address public immutable ULTRA_VERIFIER;

    // ============================================================
    //                          EVENTS
    // ============================================================

    event ProofVerified(bool success);

    // ============================================================
    //                          ERRORS
    // ============================================================

    error VerifierNotSet();
    error VerificationCallFailed();

    // ============================================================
    //                        CONSTRUCTOR
    // ============================================================

    /**
     * @param ultraVerifier_ Address of the deployed UltraVerifier contract
     */
    constructor(address ultraVerifier_) {
        if (ultraVerifier_ == address(0)) revert VerifierNotSet();
        ULTRA_VERIFIER = ultraVerifier_;
    }

    // ============================================================
    //                     VERIFICATION
    // ============================================================

    /**
     * @notice Verify a ZK proof
     * @param proof The serialized proof bytes
     * @param publicInputs The public inputs to the circuit
     * @return True if the proof is valid
     */
    function verify(bytes calldata proof, bytes32[] calldata publicInputs) external view override returns (bool) {
        // Call the auto-generated UltraVerifier's verify function
        // The UltraVerifier interface: verify(bytes calldata _proof, bytes32[] calldata _publicInputs) returns (bool)
        (bool success, bytes memory result) =
            ULTRA_VERIFIER.staticcall(abi.encodeWithSignature("verify(bytes,bytes32[])", proof, publicInputs));

        if (!success) revert VerificationCallFailed();

        return abi.decode(result, (bool));
    }
}
