// SPDX-License-Identifier: MIT
pragma solidity ^0.8.27;

import {Script, console2} from "forge-std/Script.sol";
import {ComplianceManager} from "../src/ComplianceManager.sol";
import {AssetRegistry} from "../src/AssetRegistry.sol";
import {AssetOracle} from "../src/AssetOracle.sol";
import {DividendDistributor} from "../src/DividendDistributor.sol";
import {ZKVerifier} from "../src/ZKVerifier.sol";
import {HonkVerifier} from "../src/UltraVerifier.sol";
import {ERC1967Proxy} from "@openzeppelin/contracts/proxy/ERC1967/ERC1967Proxy.sol";

/**
 * @title DeployAll
 * @notice Deploys all BharatRWA infrastructure contracts in the correct order.
 *
 *         Deployment order:
 *         1. HonkVerifier (real ZK verifier from Barretenberg) + ZKVerifier wrapper
 *         2. ComplianceManager (UUPS proxy)
 *         3. AssetOracle
 *         4. AssetRegistry (UUPS proxy)
 *         5. DividendDistributor
 *
 * @dev Usage:
 *      # With real HonkVerifier:
 *      USE_REAL_VERIFIER=true forge script script/DeployAll.s.sol:DeployAll \
 *          --rpc-url $SEPOLIA_RPC_URL --broadcast --verify
 *
 *      # With mock verifier (for quick testnet testing):
 *      forge script script/DeployAll.s.sol:DeployAll \
 *          --rpc-url $SEPOLIA_RPC_URL --broadcast
 */
contract DeployAll is Script {
    function run() external {
        uint256 deployerPrivateKey = vm.envUint("PRIVATE_KEY");
        address deployer = vm.addr(deployerPrivateKey);

        // Check if we should use the real HonkVerifier
        bool useRealVerifier = vm.envOr("USE_REAL_VERIFIER", false);

        console2.log("Deployer:", deployer);
        console2.log("Balance:", deployer.balance);
        console2.log("Using real HonkVerifier:", useRealVerifier);

        vm.startBroadcast(deployerPrivateKey);

        // ============================================================
        // 1. Deploy ZK Verifier
        // ============================================================
        address verifierAddr;

        if (useRealVerifier) {
            // Deploy the real HonkVerifier generated by Barretenberg
            // (generated via: make zk-verifier)
            HonkVerifier honkVerifier = new HonkVerifier();
            verifierAddr = address(honkVerifier);
            console2.log("HonkVerifier (real) deployed at:", verifierAddr);
        } else {
            // Deploy a mock verifier for quick testnet testing
            MockVerifierForDeploy mockVerifier = new MockVerifierForDeploy();
            verifierAddr = address(mockVerifier);
            console2.log("MockVerifier deployed at:", verifierAddr);
        }

        // Deploy ZKVerifier wrapper
        ZKVerifier zkVerifier = new ZKVerifier(verifierAddr);
        console2.log("ZKVerifier wrapper deployed at:", address(zkVerifier));

        // ============================================================
        // 2. Deploy ComplianceManager (UUPS Proxy)
        // ============================================================
        ComplianceManager complianceImpl = new ComplianceManager();
        bytes memory complianceInit =
            abi.encodeWithSelector(ComplianceManager.initialize.selector, deployer, address(zkVerifier));
        ERC1967Proxy complianceProxy = new ERC1967Proxy(address(complianceImpl), complianceInit);
        ComplianceManager compliance = ComplianceManager(address(complianceProxy));
        console2.log("ComplianceManager (proxy):", address(complianceProxy));
        console2.log("ComplianceManager (impl):", address(complianceImpl));

        // ============================================================
        // 3. Deploy AssetOracle
        // ============================================================
        uint256 heartbeat = 3600; // 1 hour
        AssetOracle oracle = new AssetOracle(deployer, heartbeat);
        console2.log("AssetOracle deployed at:", address(oracle));

        // ============================================================
        // 4. Deploy AssetRegistry (UUPS Proxy)
        // ============================================================
        AssetRegistry registryImpl = new AssetRegistry();
        bytes memory registryInit =
            abi.encodeWithSelector(AssetRegistry.initialize.selector, deployer, address(compliance));
        ERC1967Proxy registryProxy = new ERC1967Proxy(address(registryImpl), registryInit);
        AssetRegistry registry = AssetRegistry(address(registryProxy));
        console2.log("AssetRegistry (proxy):", address(registryProxy));
        console2.log("AssetRegistry (impl):", address(registryImpl));

        // ============================================================
        // 5. Deploy DividendDistributor
        // ============================================================
        DividendDistributor distributor = new DividendDistributor(deployer);
        console2.log("DividendDistributor deployed at:", address(distributor));

        // ============================================================
        // Summary
        // ============================================================
        console2.log("");
        console2.log("========================================");
        console2.log("  BharatRWA Deployment Complete");
        console2.log("========================================");
        console2.log("ZKVerifier:          ", address(zkVerifier));
        console2.log("ComplianceManager:   ", address(complianceProxy));
        console2.log("AssetOracle:         ", address(oracle));
        console2.log("AssetRegistry:       ", address(registryProxy));
        console2.log("DividendDistributor: ", address(distributor));
        console2.log("========================================");

        vm.stopBroadcast();
    }
}

/**
 * @notice Minimal mock UltraVerifier for testnet deployment
 * @dev Always returns true. Replace with real Barretenberg verifier for production.
 */
contract MockVerifierForDeploy {
    function verify(bytes calldata, bytes32[] calldata) external pure returns (bool) {
        return true;
    }
}
