// SPDX-License-Identifier: MIT
pragma solidity ^0.8.27;

import {Test, console2} from "forge-std/Test.sol";
import {ZKVerifier} from "../src/ZKVerifier.sol";
import {HonkVerifier} from "../src/UltraVerifier.sol";

/**
 * @title ZKVerifierIntegrationTest
 * @notice Tests that our ZKVerifier wrapper correctly integrates with the
 *         real HonkVerifier generated by Barretenberg.
 *
 *         NOTE: This test deploys the real HonkVerifier contract but doesn't
 *         test with a real proof (proof generation requires more RAM than
 *         available). It verifies:
 *         1. The HonkVerifier deploys and is callable
 *         2. Our ZKVerifier wrapper correctly delegates to it
 *         3. Invalid proofs are correctly rejected
 */
contract ZKVerifierIntegrationTest is Test {
    ZKVerifier public zkVerifier;
    HonkVerifier public honkVerifier;

    function setUp() public {
        // Deploy the REAL auto-generated HonkVerifier
        honkVerifier = new HonkVerifier();
        console2.log("HonkVerifier deployed at:", address(honkVerifier));

        // Deploy our ZKVerifier wrapper pointing to the real HonkVerifier
        zkVerifier = new ZKVerifier(address(honkVerifier));
        console2.log("ZKVerifier deployed at:", address(zkVerifier));
    }

    function test_DeploymentLinksCorrectly() public view {
        assertEq(zkVerifier.ULTRA_VERIFIER(), address(honkVerifier));
    }

    function test_RejectInvalidProof() public {
        // An invalid proof should cause VerificationCallFailed
        bytes memory invalidProof = new bytes(32);
        bytes32[] memory publicInputs = new bytes32[](6); // 22 - 16 pairing points = 6
        publicInputs[0] = bytes32(uint256(0x1234));

        // The HonkVerifier should revert on an invalid proof size/format
        vm.expectRevert();
        zkVerifier.verify(invalidProof, publicInputs);
    }

    function test_HonkVerifierIsViewFunction() public view {
        // Verify that the HonkVerifier's verify function is callable as view
        // (important since our ZKVerifier uses staticcall)
        // This just confirms the deployment and ABI are correct
        assertTrue(address(honkVerifier) != address(0));
        assertTrue(address(honkVerifier).code.length > 0);
    }
}
